### ISSUE TITLE
Les joyaux méconnus de Rails

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#1]
Les trucs trop puissants qui viennent avec Rails, mais qu'on ne connait pas forcément parce que toute l'attention est prise par ActiveRecord et ActionPack : les méthodes ultra cool de ActiveSupport, GlobalID, Attributes API, etc.

**Comment by abelards** [comment]
J'ai du mal à savoir ce qui est connu et méconnu :)
- `rails console --sandbox` ? 
- `rails notes` ?
- `has_many :through` ? 
- `ActiveRecord::Relation::explain` ?

Sur les ajouts de ActiveSupport
- on connaît `blank?` et les méthodes de date/time mais on oublie que c'est du ActiveSupport :)
- `squish` et `truncate(size, separator: ' ')` sur String ?
- `to_s` sur les nombres, et ses arguments `currency`, `percentage`... ?

**Comment by begault** [comment]
https://blog.bigbinary.com/2016/06/21/rails-5-supports-adding-comments-migrations.html <3
Tout con mais pour les data scientists qui bossent avec l'équipe tech c'est super

**Comment by bobmaerten** [comment]
Toute les méthodes date/timezone qui facilitent la vie des dev
genre `Date.current.end_of_month` ou de déplacement temporel style `2.days.ago` ou de calcul `Time.current.yesterday + 2.hours`

**Comment by r3trofitted** [comment]
Bon, bah ce ne sont pas les sujets qui manquent ! @abelards, @begault @bobmaerten, on enregistre celui-ci ensemble ?

**Comment by bobmaerten** [comment]
Faudrait creuser encore quelques pépites, non ? Et voir comment présenter tout cela à l'audio 😛

**Comment by abelards** [comment]
Puisque vous aimez les calculs j'ajoute nécessairement /faveod/arel_extensions 😛 
C'est pas dans Rails mais j'aimerais beaucoup que ce soit par défaut dans arel :D

**Comment by abelards** [comment]
Tentative de plan 

* la gem du jour :
  - https://github.com/Faveod/arel-extensions/

* autour de Rails : 
  - `rails console --sandbox` : le côté rassurant de ne rien casser
  - `rails notes` : pouvoir se garder des notes dans le code
  - `rails -T` : pour avoir la liste des commandes Rails
  - migrations, commentaires sur les migrations [1]
    (cf @begault et surtout comment ça s'utilise en équipe)

* Modèle
  - has_many :through
  - `delegate :attribute, to: :association` ? https://guides.rubyonrails.org/active_support_core_extensions.html#delegate
  - deprecate
  - concerning
  - ActiveRecord::Relation::explain
  - calculs de date [2a] [2b] [2c]

* Vue
  - squish et truncate(size, separator: ' ') sur String [4]
  - to_s sur les nombres, et ses arguments currency, percentage... [5a] [5b] [5c]
  - simple_format [6]
  - sanitize [7]
  - `html_safe` peut-être ? C'est sûrement connu dans l'effet mais pas dans les mécanismes ?
  - `array.in_groups_of(x)` [8]

* Contrôleur
  - Je n'ai pas d'idée :)
  - to_param ? [9]
  - .in? [10]

* Autres de ActiveSupport
  - plein de trucs sur les String, p.ex. Inquiry
  - y'a des trucs vraiment jouet, des trucs vraiment techniques (threads, config, etc)
  - vous connaissiez le Tagged Logger ? [11]
  - tidy_bytes [12]

[1] https://blog.bigbinary.com/2016/06/21/rails-5-supports-adding-comments-migrations.html
[2a] https://api.rubyonrails.org/classes/ActiveSupport/Duration.html
[2b] https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-date-calculations
[2c] https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-datetime-calculations
[3] https://github.com/faveod/arel-extensions
[4] https://api.rubyonrails.org/classes/String.html
[5a] https://api.rubyonrails.org/classes/ActiveSupport/NumberHelper.html
[5b] https://api.rubyonrails.org/classes/ActiveSupport/NumericWithFormat.html
[5c] https://guides.rubyonrails.org/active_support_core_extensions.html#formatting
[6] https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format
[7] https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize
[8] https://guides.rubyonrails.org/active_support_core_extensions.html#grouping
[9] https://guides.rubyonrails.org/active_support_core_extensions.html#to-param
[10] https://guides.rubyonrails.org/active_support_core_extensions.html#in-questionmark
[11] https://api.rubyonrails.org/classes/ActiveSupport/TaggedLogging.html
[12] https://api.rubyonrails.org/classes/ActiveSupport/Multibyte/Chars.html#method-i-tidy_bytes

**Comment by bobmaerten** [comment]
Pour les contrôleurs on peut évoquer l’usage de `respond_to`

**Comment by r3trofitted** [comment]
Moi je taperais volontiers dans ActiveSupport, y compris dans les trucs plus controversés comme `AS::Concern`.

**Comment by bobmaerten** [comment]
Hey et si tout rentre pas dans un épisode, on en fera une suite :)

**Comment by r3trofitted** [comment]
Du coup, @bobmaerten, @begault et @abelards : dispos jeudi prochain (le 14/02) à 21h pour enregistrer ?

**Comment by r3trofitted** [comment]
> * `to_s` sur les nombres, et ses arguments `currency`, `percentage`... ?

Trop bien, je ne connaissais pas !

**Comment by r3trofitted** [comment]
Enregistrement le **13/02** !

**Comment by bobmaerten** [comment]
@r3trofitted tu pourras faire un résumé dans le 1er message du ticket qui servira de plan ?

**Comment by begault** [comment]
Autre joyau méconnu: https://apidock.com/rails/ActiveSupport/Multibyte/Unicode/tidy_bytes

```
Replaces all ISO-8859-1 or CP1252 characters by their UTF-8 equivalent resulting in a valid UTF-8 string.

Passing true will forcibly tidy all bytes, assuming that the string’s encoding is entirely CP1252 or ISO-8859-1.
```
