### ISSUE TITLE
Construire une équipe

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#10]
Comment faire en sorte d'avoir l'équipe la plus efficace possible ? Combien de senior/mid/junior faudrait il ? Comment faire pour qu'ils aient un sentiment d'appartenance et ce même en remote ? 

👨 👩 🐿 🤖

**Comment by abelards** [comment]
- combien de gens ? avec quelles casquettes / fonctions ?
   (sujet annexe mais proche et qui impacte : quelle est la relation contractuelle, les prestas)
- de quels niveaux ? avec quelle logique d'apprentissage ?
   (une équipe de seniors c'est bien ou mal ? Ou que de juniors ? et le mentoring ?)
- culture : à quel point on la créé (top-down) ou elle émerge (bottom-up) ?
   (la culture, c'est qui ? ben... c'est nous)
- comment conserver un pipeline continu ?
    (et quand on n'est pas un GAFA qui recrute sans cesse, que faire pour anticiper ?)
- efficacité : y a-t-il des astuces pour en gagner / des bêtises pour en perdre
  (réunionnite, open space?, séparation avec le client, etc...)

Sinon on aura les épisodes productivité / générativité / management : outils, méthodes...
J'avais entendu cette super astuce :
> "demande à tes devs ce qui leur prend du temps et qui n'est pas du dev, et embauche une personne pour faire juste ça"
