### ISSUE TITLE
Trucs pour augmenter la productivité

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#11]
Présentation d'outils et de conseils pour aller plus vite (faire des pauses, bien dormir, connaitre son éditeur de texte, etc.).

**Comment by abelards** [comment]
* santé (dormir boire manger exercice pauses)
* outils (éditeur CLI IDE gems...)
* manières de prioriser ? de communiquer ?
* pièges à temps (les trouver, les résoudre)
* réunions => http://larahogan.me/blog/better-meetings/

**Comment by jumichot** [comment]
- Gérer les interruptions : internes (outils et méthodes pour rester focus, pomodoro) et externes (casque réduction de bruits, musique stimulante comme brain.fm)
- méthodes d'organisation personnelles (GTD, Personnal Kanban)

**Comment by Samy-Amar** [comment]
* Petits hacks pour gagner beaucoup de temps (alias bash, plug-ins outils)

**Comment by benoittgt** [comment]
* Regarder les conseils de Justing Searls : https://youtu.be/VD51AkG8EZw?t=1824

**Comment by damln** [comment]
Je suis super motivé pour participer à ce numéro. J'ai un article de blog assez "brute" mais à jour avec mes tools:
[https://damln.com/log/setup](https://damln.com/log/setup)

A voir si on peut partager dessus j'adore le sujet en tout cas :)

**Comment by flexbox** [comment]
Alfred + Workflow + Dash = ⚡️⚡️⚡️

https://www.alfredapp.com/blog/productivity/dash-quicker-api-documentation-search/
