### ISSUE TITLE
Encapsulation et différences avec Python

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#12]

**Comment by celine-m-s** [comment]
Tout est public en Python ! La philosophie est un peu différente : si tu veux accéder à une méthode "privée", c'est que tu as une bonne raison de le faire et tu dois donc pouvoir le faire. Je trouve cette différence assez sympa. Ca ne vaut peut-être pas le coup d'en faire tout un épisode ceci dit...

**Comment by r3trofitted** [comment]
Mais, mais… C'est exactement pareil en Ruby, voyons !

**Comment by celine-m-s** [comment]
Comme quoi, pas besoin d'en faire un épisode ! ;-)
J'archive le sujet.

**Comment by r3trofitted** [comment]
Pardon, je ne voulais pas sonner comme un tel connard. Cela dit, cette approche différente de la visibilité des membres est un bon sujet, si on comparé Ruby (et Python, donc) à des langages hérités du C++, par exemple.
