### ISSUE TITLE
Apprendre Python quand on vient de Ruby

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#13]

**Comment by celine-m-s** [comment]
Ces deux langages sont souvent comparés pour leur ressemblance mais pourtant ils sont assez différents. Comparaison rapide des deux et pièges à éviter :)

**Comment by r3trofitted** [comment]
Premier piège : faire du Python. :trollface:

**Comment by celine-m-s** [comment]
Je sens que tu es chaud pour faire cet épisode ! :) (en même temps, est-ce qu'il y a un truc dont tu n'aimes pas débattre ? 🤔 )

**Comment by bobmaerten** [comment]
C'est comme se battre avec un cochon dans la boue, après 15 minutes tu te
rends compte qu'il aime ça. 😁

**Comment by abelards** [comment]
Il y a beaucoup de choses qu'on partage. Même si j'ai envie de taquiner les pythonistes sur 5 vs 19, et leurs fonctions dans le namespace global.

http://www.thezenofpython.com/

The Zen of Python
	    1. Beautiful is better than ugly.
	    2. Explicit is better than implicit.
	    3. Simple is better than complex.
	    4. Complex is better than complicated.
	    5. Flat is better than nested.
	    6. Sparse is better than dense.
	    7. Readability counts.
	    8. Special cases aren't special enough to break the rules.
	    9. Although practicality beats purity.
	    10. Errors should never pass silently.
	    11. Unless explicitly silenced.
	    12. In the face of ambiguity, refuse the temptation to guess.
	    13. There should be one-- and preferably only one --obvious way to do it.
	    14. Although that way may not be obvious at first unless you're Dutch.
	    15. Now is better than never.
	    16. Although never is often better than *right* now.
	    17. If the implementation is hard to explain, it's a bad idea.
	    18. If the implementation is easy to explain, it may be a good idea.
	    19. Namespaces are one honking great idea -- let's do more of those!

**Comment by yaf** [comment]
Et bien, pour avoir pas mal de pote qui font du python, pour avoir hésité entre python et ruby en 2004, et pour finalement faire plutôt du python que du ruby depuis 1,5 ans, ça me fera plaisir de partager cette expérience avec vous :-D

**Comment by jbbarth** [comment]
Au delà de la philosophie, un peu pareil que @yaf, je ne fais quasi que du python depuis 2 ans pour des raisons professionnelles, et il y a plein de choses intéressantes à dire techniquement. A commencer par le modèle objet et les principes du langage (scopes, binding des méthodes, passage des arguments, écosystèmes...)

**Comment by abelards** [comment]
J'aimerais aussi inviter @begault :)

**Comment by nicoolas25** [comment]
J'aimerais bien écouter cet épisode !
