### ISSUE TITLE
Match Django / Rails

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#14]

**Comment by jbbarth** [comment]
Intéressant ça :-) J'ai fait du Rails pendant 6-7 ans avant de me perdre dans une boite qui fait que du Django, j'ai donc un avis un peu biaisé par plus d'aisance en Rails, mais il y a quand même des tas de choses intéressantes à dire (et à apprendre!?) de Django pour les gens qui font surtout du Rails ... et inversement.
