### ISSUE TITLE
014 - La solitude, ennemi du freelance ?

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#15]

**Comment by celine-m-s** [comment]
Etre freelance c'est cool mais cela peut aussi être un piège. Faut-il travailler de chez soi ? Comment être efficace quand on est seul ? 
Comment reconnaitre les signes indiquant qu'il faut sortir pour s'aérer ? 
La solitude peut vite apparaitre sans qu'on s'en rende compte et menacer la vie d'un projet. 
(Bon là ça fait tarte à la crème mais je pense qu'il y a aussi moyen de le séparer en deux sujets : le travail en remote et la gestion de son temps en tant que freelance)

**Comment by abelards** [comment]
* bus-factor (est-ce que le projet peut continuer sans toi ?)
* sentiment de communauté pour lutter contre la solitude (soutien et compréhension de famille époux amis difficile s'ils ne sont pas freelance)

**Comment by benoittgt** [comment]
Dispo aussi pour en discuter. Je suis en remote. ;)

La boite pour laquelle je bosse avait écrit un article sur le remote. Quelques points sur la solitude : 

https://medium.com/appaloosa-store-engineering/our-jump-into-a-remote-friendly-team-6af2fa8b7d6#.9ltx7stt3

**Comment by jumichot** [comment]
Intéressé aussi pour parler de ce sujet

**Comment by abelards** [comment]
Bonjour à toutes et tous ! On se propose d'avancer l'enregistrement de cet épisode pour cette semaine. Quand sont vos dispos ? On se voit sur #lerubynouveau sur le Slack ? ++

**Comment by Sylvain-Kraisin** [comment]
Bonjour à tous. Intéressé par le sujet et pour participer (Dev RoR Jr qui a ete 6 mois Freelance puis actuellement en CDI)
