### ISSUE TITLE
Enseigner pour apprendre, enseigner pour comprendre

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#17]

**Comment by celine-m-s** [comment]
En quoi le fait d'enseigner nous aide-t-il à progresser dans notre métier ? Pourquoi écrire des articles ou participer à des conférences (ou à des podcasts !) nous permet-il de mieux comprendre le développement ?

**Comment by abelards** [comment]
- quels sont les contenus nécessaires, comment aiguiller ?
- y a-t-il des must-have et des trucs à pas faire ?
- qu'attend-on des enseignants ? (compétences, attitudes)
- qu'attend-on des apprenants ? (idem)
- quels types de communication marchent ou marchent pas ?
- est-ce qu'un canard en plastique peut suffire ? 🦆

J'aime beaucoup : 
- (prof) poser souvent des questions simples pour donner l'habitude de participer
- (élèves) prendre ainsi l'habitude de participer et de pas se taire par peur, et rester actifs
...

**Comment by yaf** [comment]
Je pose mon nom par ici aussi du coup. Toujours intéressé pour parler de ce genre de sujet :-)

**Comment by soveran** [comment]
@yaf Tu peux te mettre comme "Assignee" ! (en haut à droite)

**Comment by yaf** [comment]
Je n'ai pas le droit apparement....

**Comment by soveran** [comment]
@yaf C'est vrai, désolé -_-

**Comment by Ynote** [comment]
Ayant participé récemment à plusieurs Women on Rails, je me propose pour participer ici. Histoire de raconter : 
- pourquoi j'ai eu envie de le faire,
- pourquoi à partir du moment où on a appris quelque chose, l'enseigner est enrichissant,
- comment un cours/atelier à deux ou à plusieurs montre que l'énergie collective permet de créer un produit meilleur (dans notre cas du code meilleur).
