### ISSUE TITLE
008 - Productivité / Générativité

### ISSUE THREAD

**Issue by abelards** [LeRubyNouveau/liste-de-souhaits#18]
Super discussion sur Greater Than Code 019
http://www.greaterthancode.com/podcast/episode-019-its-made-of-people/

**Generativity:** The difference between your team’s output with you on it and your team’s output without you.

"The easiest way to be a 10x programmer is to make 5 people 2x programmers"

Le rôle du lead tech / architecte...

**Comment by toch** [comment]
Si je comprends bien ce que c'est, j'appelle cela accélération de développement, c-a-d tout ce qu'on peut faire pour que les développeurs puissent être productifs. Par exemple :

* des outils adaptés (du CI qui crunch du job et qui est fiable, aux outils ad hoc qui permettent de scaffolder un projet dans un langage donné)
* une plateforme sur laquelle il est plus facile à développer,
* un environnement de projet facile à préparer (et pas une semaine pour l'installer),
* un onboarding des nouveaux histoire de bien transmettre le savoir faire et la culture de développement de la boite,
* un process de projet où on peut apprendre,
* la formation active où les développeurs peuvent apprendre de nouvelles tech ou coder dans de nouveaux langages,
* etc.
