### ISSUE TITLE
007 - Que tester, comment tester ?

### ISSUE THREAD

**Issue by abelards** [LeRubyNouveau/liste-de-souhaits#20]
Issu du super podcast de Andrzej on Software :

"plus je sens que le projet / l'architecture va changer, plus je teste à haut niveau (intégration, scénarii), plus je sens que le projet se stabilise plus je descends dans les test unitaires"

**Comment by abelards** [comment]
Une petite pensée pour tous les GIF "tous les tests unitaires passent".

**Comment by toch** [comment]
j'aime l'approche de l’oignon: on commence par tester l'API extérieure, le plus important, et puis au fur et à mesure qu'on épluche, on rajoute des tests sur les couches internes, pour arriver au test unitaire.

dans cette même philosophie, s'il n'y avait qu'un test à écrire je m'occuperais d'un test black box/d'acceptance.

**Comment by r3trofitted** [comment]
Grande boucle, petite boucle. Pyramide des tests. École londonienne. Hmm, toutes ces expressions d'initiés (ou pas).
