### ISSUE TITLE
009 — Tests II, le retour

### ISSUE THREAD

**Issue by abelards** [LeRubyNouveau/liste-de-souhaits#27]
À voir et reprendre depuis #20 ce qui n'est pas dans l'épisode 007
https://github.com/LeRubyNouveau/liste-de-souhaits/issues/20

**Comment by abelards** [comment]
Quand on dit :

Andrzej on Software :
> "plus je sens que le projet / l'architecture va changer, plus je teste à haut niveau (intégration, scénarii), plus je sens que le projet se stabilise plus je descends dans les test unitaires"

Toch :
> j'aime l'approche de l’oignon: on commence par tester l'API extérieure, le plus important, et puis au fur et à mesure qu'on épluche, on rajoute des tests sur les couches internes, pour arriver au test unitaire.
> dans cette même philosophie, s'il n'y avait qu'un test à écrire je m'occuperais d'un test black box/d'acceptance.

est-ce que c'est ce que @r3trofitted appelle "Grande boucle, petite boucle." ?

Je ne suis pas sûr qu'on ait mentionné 
> Pyramide des tests. École londonienne. Hmm, toutes ces expressions d'initiés (ou pas).

Par contre un truc que je n'ai pas entendu dans l'épisode d'avant : 
RACCOURCIR LA FEEDBACK LOOP
c'est vrai pour tester, pour apprendre, pour garder le moral, pour prévenir le patron...

**Comment by jlecour** [comment]
J'ai envie de mentionner : 
* pourquoi je ne fais pas des tonnes de tests
* quoi tester ?
* tester du code "legacy"

**Comment by abelards** [comment]
- smoke testing / canary
- fuzzing
- mutation testing
- black box testing (sécu : white, black, gray)
- tests de charge
- ...

**Comment by toch** [comment]
stress vs load vs performance and so on

**Comment by jlecour** [comment]
Je veux bien m'occuper de la transcription pour celui là.

**Comment by jlecour** [comment]
@bobmaerten peux-tu me rappeler où je peux trouver la piste audio, s'il te plaît.
Je devrais pouvoir gérer la transcription dans la semaine (idéalement mardi soir).

**Comment by bobmaerten** [comment]
Je n'ai pas encore fait le montage. Je vais essayer d'avancer dessus
rapidement. Sinon les pistes brutes sont dispo dans le channel sur slack.

Le mar. 21 mars 2017 00:11, Jérémy Lecour <notifications@github.com> a
écrit :

**Comment by jlecour** [comment]
Je ne suis pas au point sur la logistique ; je ne sais pas où sont les "notes de l'épisode", du coup je rajoute ici.

Dans l'épisode je parlais d'une présentation "refactoring" de Katrina Owen. Voici le lien : https://www.youtube.com/watch?v=KA9i5IGS-oU
