### ISSUE TITLE
015 - La santé des devs

### ISSUE THREAD

**Issue by begault** [LeRubyNouveau/liste-de-souhaits#32]
[Donnez le contexte général du sujet]

Discuter des différents problèmes de santé que notre travail au quotidien peut apporter. 
Expliquer comment prévenir ces problèmes et comment essayer de les résoudre le cas échéant.

[Citez éventuellement des exemples illustrant le sujet abordé]

Certains développeurs ont un souci de kyste synovial => discuter des positions, de l'évolution du problème, des claviers existants ergonomiques, des souris spéciales, etc

[Précisez si vous êtes vous-même intéressé pour participer au podcast et le cas échéant votre niveau de connaissance du sujet]

Plutot intéressée

**Comment by begault** [comment]
Parler de ce sujet peut etre très long si on considère parler des santés physique et psychologique.
Ca peut du coup etre aussi un sujet sensible.
Il faudrait définir le scope de cette discussion en fonction des envies du coup.

**Comment by jumichot** [comment]
Pour les problèmes physiques, plusieurs sujets peuvent être abordés :
- syndrome du RSI (TMS) et comment l'éviter (souris verticales, clavier ergonomique)
- l'importance du sommeil
- position debout et assis (standing desk)
- faire du sport : ex : 7min workout, coder en marchant sur un treadmill,...
- méditation
- nourriture ? (le danger des snacks durant la journée ? :p )

En effet pour l'aspect psychologique c'est peut-être un peu plus difficile à scoper

Plutôt intéressé, je peux aider pour les sujets ci-dessus

**Comment by benoittgt** [comment]
Interessé également pour en parler.

**Comment by abelards** [comment]
C'était un de mes tous premiers talks, ah, les souvenirs ;)
https://speakerdeck.com/abelar_s/health-tips-from-geek-to-geek
https://vimeo.com/56858278
Ça se basait sur un article de Zed Shaw que je recommande

**Comment by borisrorsvort** [comment]
Il y a quelques éléments nouveaux sur les lumières bleues. https://www.wired.com/2017/03/uncertain-science-behind-phones-blue-light-dimmer

Aussi sur le sommeil https://sleep.org/articles/catching-up-on-sleep/
