### ISSUE TITLE
018/020 - L'apprentissage du développement chez les plus jeunes

### ISSUE THREAD

**Issue by begault** [LeRubyNouveau/liste-de-souhaits#33]
## Contexte général du sujet

Discuter des outils / programmes d'apprentissage / groupes chez les enfants (en fonction de l'age).
Donner des exemples, parler de nos propres essais. 

On peut s'aider du document qu'avait fait @fonji (https://slack-files.com/T042KF3JR-F1VTW9G8K-9d51e1fc85)

Il y a des initiatives qui existent comme celle de l'Ocado Fundation en Angleterre : https://www.codeforlife.education/
Il y a toute une communauté de bénévoles derrière ces jeux.
Celine Boudier qui a fait cette présentation (https://www.slideshare.net/CelineBoudier/inspiring-all-children-celine-boudier-code-for-life) est une amie, on peut l'inviter pour en parler. 
/cc @CelineBoudier

Coding Gouters : ut7

## Exemples illustrant le sujet abordé

J'ai actuellement tenté quelques logiciels et jeux avec ma niece et mon neveu:
- Bug : jeu de plateau voué à réparer des robots défectueux (blocs de logique) https://www.trictrac.net/jeu-de-societe/the-bugs
- Hello Ruby : livre contenant une histoire d'aventure mêlée à de la logique et des exercices de programmation accessibles dès 5 ans pour certains http://www.helloruby.com/
- Lightbot et scratchjr https://lightbot.com/flash.html / http://www.scratchjr.org/ des logiciels en webapp, sur android ou ios qui permettent de comprendre plusieurs principes dont les blocks, les boucles et les conditionnelles

## Informations diverses sur l'auteur(e) du ticket

Super intéressée, je suis en plein apprentissage des conditionelles avec mon neveu de 5 ans.

**Comment by fonji** [comment]
Coucou :wave: 

Donc je suis super intéressé mais ne me demandez pas de participer, je n'ai pas encore de témoignage à apporter.

(Sinon, heureusement que je ne me suis pas fait piquer mon nom d'utilisateur favori par quelqu'un d'autre :laughing: )

**Comment by jumichot** [comment]
Peut-être contacter les gens de chez ut7, ils font des coding gouter avec des enfants depuis un moment (@yannick sur le slack parisrb)

**Comment by yaf** [comment]
Yop. Bon, je ne suis pas sur que mon camarade soit dispo pour en parler, mais je devrais pouvoir en parler aussi.

**Comment by benoittgt** [comment]
Peut être Max de Nantes aussi qui organise également des coding gouter.

**Comment by CelineBoudier** [comment]
Je serais ravie de participer pour parler entre autres de nos jeux à Code For Life :)

**Comment by abelards** [comment]
Merci à tous pour ces deux beaux épisodes ! Je nettoie un peu, mais surtout que ça ne nous empêche pas de faire un jour un 3e épisode sur l'apprentissage et/ou les plus jeunes :)
