### ISSUE TITLE
La gestion de version du code source

### ISSUE THREAD

**Issue by jlecour** [LeRubyNouveau/liste-de-souhaits#36]
## Contexte général du sujet

Comment gérer les flux de travail autour du code ?

À la fois l'utilisation basique des outils, mais aussi la manière de faire collaborrer une équipe, les motifs de fonctionnement, les techniques de communication…

## Exemples illustrant le sujet abordé

GIT, git-flow

## Informations diverses sur l'auteur(e) du ticket

Je suis intéressé(e) pour participer au podcast.
J'ai activement participé à la mise en place de ces outils et pratiques dans plusieurs équipes.
Une de mes présentations publiques est dispo sur https://speakerdeck.com/jlecour/introduction-a-git-et-workflows-marsjug-2011 (c'est très vieux mais toujours valable).

- [x] Oui !

Votre niveau de connaissance/maîtrise du sujet

- [ ] Aucune connaissance, je ne fais que proposer pour en entendre parler
- [ ] Je m'y intéresse vaguement
- [ ] Débutant(e)
- [ ] Intérmédiaire
- [x] Expert(e)
- [ ] Référence dans le domaine

**Comment by bobmaerten** [comment]
Ils ont trop la classe ces nouveaux templates de ticket ;)
ça m'intéresse bien de participer à ce débat, j'ai toujours aimé parler outillage.

**Comment by flexbox** [comment]
Au besoin j'ai un usecase : *Ajouter de la magie avec* `git-extras`, il faut un peu de rigueur mais cela permet de mettre son projet en autopilot :
1. hysterie des messages de commit avec la [convention karma](http://karma-runner.github.io/1.0/dev/git-commit-msg.html)
1. Generation automatique de changlog
1. Release + tag
