### ISSUE TITLE
Les environnements de travail en 2019

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#4]
Open space, remote, coworking…

**Comment by abelards** [comment]
Est-ce que ça collerait à ton idée :
- digital nomad (Jumichot et Cécile),
- remote mi-temps, majoritaire ou complet,
- astuces pour rendre son bureau plus sympa (affiches, plantes vertes)
- vie de groupe pour les collègues (repas, salle consoles, verres le soir)
- et le fameux emplacement stratégique de la machine à café !
(je pense que les 3 premiers oui, l'avant dernier pas forcément)

**Comment by r3trofitted** [comment]
En fait, je crois que ce n'était pas _mon_ idée ; par contre, c'est justement l'avant-dernier dernier point qui m'intéresse le plus !
