### ISSUE TITLE
Les méthodes de travail

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#5]
_Pair programming_, _pull requests_, _kanban_, et pas un seul terme français (ah, si, « cycle en V »)

**Comment by abelards** [comment]
- recueillir le besoin : réunions, specs, relectures ?
- documenter un projet ensemble : wiki ?
- coder ensemble : pair programming, mob programming, code reviews
- outils de collaboration : git, ticketing...
- suivre un projet ensemble : kanban, scrum et autres, ...
- faire tourner une appli ensemble : tickets, bugs, astreintes, urgences ?
- formation continue au sein de la boîte ?

Comme souvent : participez, ajouter des sujets, affinons ensemble,
et découpons cette vaste idée de Ronan en plusieurs épisodes de 45mn :)
(et oui, ce commentaire est méta parce que c'est une manière de bosser ensemble ^^)

**Comment by r3trofitted** [comment]
Et aussi : les limites de « l'agile »

**Comment by alex-lairan** [comment]
Sujet très intéressant ! :) 

Une chose importante aussi:
- L'écoute

Sans doute le plus important :)

**Comment by abelards** [comment]
Un petit coup de RUP ? :)
Pour parler de Scrum pourquoi pas @morendil ?

**Comment by yaf** [comment]
@morendil parlera plus facilement d'XP :-p
