### ISSUE TITLE
011 - accueillir un junior en entreprise

### ISSUE THREAD

**Issue by abelards** [LeRubyNouveau/liste-de-souhaits#55]
### RÉSUMÉ DE L’EPISODE PRECEDENT
- Pourquoi embaucher un junior ?
- Quel serait l’accueil parfait ?
- Les étapes pour intégrer au mieux un junior (accueil, découverte du projet, mentor désigné ?,...)
- Les savoirs qui s’apprennent et ceux qui s’apprennent moins 
- Une fois qu’il est là, qu’est-ce qu’on fait ? se sentir utile ? lui donner quoi ?
- Combien de temps avant d'enlever les petites roulettes ?

##### Quels sont les contenus nécessaires, comment aiguiller ?
- Qu'attend-t-on des enseignants ? (compétences, attitudes...)
- LA PATIENCE :)
- NE JAMAIS piquer le clavier
- Environnement
- des priorités claire et du fallback (de la doc ?)

http://clojurebridge-berlin.org/coaches_training.deck.html#discussion_topics

##### Qu'attend-on des apprenants ? (idem)
- Le laisser dans son coin ou être proche ?
- Quels types de communication marchent ou marchent pas ?

##### Méthodes
- Quels sont les meilleures méthodes à adopter ?
- Quel ratio entre pair programming et travail seul ?
- Est-ce qu'un canard en plastique peut suffire ? 

-- tous les podcasts avec Sandi Metz ou Katrina Owen

Bonus : Quand doit-on quitter le navire ?
http://softskills.audio/2017/01/02/episode-42-job-hopping-and-cultural-reliability/
Should I switch jobs to my fourth job within two years of graduating from a bootcamp?
What non-technical practices and cultural attributes improve software reliability?

**Comment by flexbox** [comment]
##### Méthodes
- Mise en place de sessions de mob programming ?

**Comment by toch** [comment]
# Méthodes

* objectifs d'acquistion

**Comment by nicoolas25** [comment]
Est-ce que le sujet n'est pas tellement vaste qu'un 3ème épisode n'aiderait que très peu ?

**Comment by bobmaerten** [comment]
On va attendre les retours des auditeurs peut-être ? Ou alors scinder sur
des parties spécifiques comme le longue partie sur le pair-programming ou
on pourra entrer dans les détails et des retours d'expériences concrets
plutôt que de rester dans les généralités ?

Le jeu. 30 mars 2017 à 09:04, Nicolas Zermati <notifications@github.com> a
écrit :

**Comment by soniaprevost** [comment]
Je suis d'accord avec vous deux. On n'a pas forcément besoin de faire un nouveau sujet sur le junior en entreprise car finalement ce dont on a parlé à la fin (pair programming et un bout de code review) fait partie d'un ensemble de sujets sur le management d'équipe. Et je suis sûre qu'en une heure de temps, on n'épuiserait pas le sujet des codes review, du pair programming, etc.
