### ISSUE TITLE
Le management

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#6]
Le management en général, et le management _des développeurs_ en particulier. C'est quoi un bon manager ? Un bon « managé » ?

**Comment by abelards** [comment]
* être managé : parce que tout commence par là
* manager : parce que ça peut vous arriver
* la transition : argh. Vous êtes un bon dev, on vous propulse manager, vous ne savez pas faire.

Heureusement plein de gens publient leur expérience : @lara_hogan @geek_manager ... et plein d'autres histoires ("Managing humans" le livre de randsinrepose).

Ce WikiHow est étonnamment clair et concis :) http://www.wikihow.com/Manage-Geeks

J'ai entendu plusieurs fois parler de TAoPM, PMBOK et Peopleware :
 http://blog.geekmanager.co.uk/recommended-books/

**Comment by jlecour** [comment]
Après plusieurs années, mon précédent patron m'a poussé à avoir un rôle de plus en plus managerial. J'ai énormément résisté mais ça s'est quand même fait petit à petit et j'ai fini par bien le vivre. 

Aujourd'hui j'ai changé de boîte (pas à cause de ça) et je continue d'avoir un rôle d'accompagnant/guide (leadership) plus que gestionnaire (manager), mais l'idée reste la même : ne pas tout faire et préférer faciliter l'efficacité du travail des autres, tout en y participant activement.

Encore un sujet passionnant et bien vu pour le podcast !!!

**Comment by abelards** [comment]
J'aimerais bien inviter @marcgg pour cet épisode-là, parce que
http://marcgg.com/blog/2017/08/20/blogging-about-management/ :)

**Comment by marcgg** [comment]
Avec plaisir :)
