### ISSUE TITLE
016 - Santé des devs #2 - santé mentale

### ISSUE THREAD

**Issue by abelards** [LeRubyNouveau/liste-de-souhaits#65]
Nous avons enregistré l'épisode 015 avec @begault et @nicoolas25 sur la santé "physique"
https://github.com/LeRubyNouveau/liste-de-souhaits/issues/32

Est-ce que ça vous tente, jeudi 25, environ 14h @jumichot @benoittgt @borisrorsvort ?

Dans les sujets dont on voulait parler :
- méditation / mindful*
- développement personnel

Changement d’environnement :
- rencontrer des personnes d’un milieu social ou professionnel différent
- type de meetups
- “randonnées” pour sortir du bureau, etc

- ADHD // spectre autisme
- depression
- Burnout : sentiment de ne pas en faire assez, rester tard sans etre productif,
   pressions sociales/professionnelles difficiles à relativiser

**Comment by jumichot** [comment]
ça devrait être possible pour moi

**Comment by GCorbel** [comment]
Je m'ajoutes. Je suis représentant des personnes avec un trouble du déficit de l'attention !
