### ISSUE TITLE
Les bootcamps

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#71]
Acteurs incontournables dans l'écosystème Ruby, il y a beaucoup à dire sur les bootcamps. Que valent leurs formations ? Comment contribuent-ils à la communauté ?

**Comment by ssaunier** [comment]
👋 Hello !

@lewagon sera ravi d'y participer (@Papillard ou moi-même)👌 

Merci !

**Comment by Samy-Amar** [comment]
Chaud pour en parler - j'ai lancé ma boîte en sortant de Bootcamp, je pense que ça peut être une discussion intéressante

**Comment by begault** [comment]
J'ai plusieurs collegues qui se sont réorientés via des bootcamps. Je peux leur parler de cette discussion sans souci si on veut la lancer d'ici peu  :)

**Comment by williampollet** [comment]
Merci @begault ! Chaud pour en parler aussi si mon retour peut intéresser.
