### ISSUE TITLE
Cuvée 2019 : le calendrier des enregistrements !

### ISSUE THREAD

**Issue by r3trofitted** [LeRubyNouveau/liste-de-souhaits#73]
## 2019, année du Ruby ~Nouveau~ Tout Neuf !

Le groupe se reforme et le podcast repart. Pour que tous ceux et celles qui souhaitent participer puissent le faire, voici le calendrier des enregistrements prévus.

Les sujets sont mentionnés _à titre indicatif_. La source de vérité unique est le [projet GH](https://github.com/LeRubyNouveau/liste-de-souhaits/projects/1), où les sujets sont organisés dans l'ordre d'enregistrement prévu.

## Février 

- [x] ~Jeudi 14/02~ Mercredi 13/02 (21h) – [Les joyaux méconnus de Rails](https://github.com/LeRubyNouveau/liste-de-souhaits/issues/1)
- [ ] ~Dimanche 17/02 (11h)~ Mardi 25/02 à 9h30 – [Télétravail](
https://github.com/LeRubyNouveau/liste-de-souhaits/issues/52)
- [ ] Samedi 23/02 (15h) – [Hanami](
https://github.com/LeRubyNouveau/liste-de-souhaits/issues/41)
- [ ] Mercredi 27/02 (20h) – [Les entretiens d'embauche](
https://github.com/LeRubyNouveau/liste-de-souhaits/issues/54)

**Comment by alex-lairan** [comment]
Hey ! Super ca !

Je suis disponible pour Hanami :)

**Comment by r3trofitted** [comment]
Je m'en doutais 😉

**Comment by bobmaerten** [comment]
Je propose, comme nous l'avons souligné dans la discussion de recadrage du podcast, d'aller évoquer les point que l'on souhaiterait chacun aborder dans l'émission directement en commentaire sur les tickets concernés.

Dans les quelques jours avant la date d'enregistrement prévue, le maitre de cérémonie compilera une sélection des points dans le 1er message du ticket qui servira à la fois comme notes pour l'enregistrement de l'émission et de base pour les notes attachées au podcast.

**Comment by flexbox** [comment]
Canon pour le planning!

Je suis dispo à cette date pour #54 

Vous êtes formidable 👍

**Comment by abelards** [comment]
Jeudi 14 c'est la Saint Valentin. Je sais que Ruby n'est qu'Amour mais je propose une autre date :)
Sinon j'aime beaucoup le jeudi soir en général.
